import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SupabaseSessionProvider } from "./providers/SupabaseSessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SupabaseSessionProvider>{children}</SupabaseSessionProvider>
      </body>
    </html>
  );
}
